channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::numpy=1.24.3
- conda-forge::pandas=1.5.3
- conda-forge::scikit-learn=1.2.2
- conda-forge::scipy=1.10.1
- conda-forge::tensorboard=2.20.0
- pip
- pip:
  - fire==0.5.0
  - torch==2.0.1